description-file = "README.md"
requires-python = ">=3.7,<3.11"

[tool.isort]
profile = "black"
line_length = 120
skip = ["src", "venv"]
known_third_party = ["pydantic"]
known_first_party = ["test"]

[tool.black]
line-length = 120
target-version = ["py39"]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | src
  )/
)
'''